spring:
  application:
    name: PestDetectionSystem
  datasource:
    url: jdbc:mysql://localhost:3306/pest_detection_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gzy.pestdetectionsystem.entity
  global-config:
    db-config:
      id-type: input
server:
  port: 8888
  servlet:
    context-path: /api

jwt:
  secret: SHUCOLLEGEOFCOMPUTERENGINEERINGANDSCIENCE22123131
  expiration: 7200000  # 2小时（毫秒）

llm:
  base-url: https://api.minimaxi.com/v1
  api-key:
  chat-path: /chat/completions
  model: MiniMax-M2.7
  temperature: 1.0
  max-tokens:  1024

