spring:
  application:
    name: PestDetectionSystem
  datasource:
    url: jdbc:mysql://localhost:3306/pest_detection_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8            # 最大连接数
          max-wait: -1ms           # 最大等待时间
          max-idle: 8             # 最大空闲连接
          min-idle: 0             # 最小空闲连接

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gzy.pestdetectionsystem.entity
  global-config:
    db-config:
      id-type: input
server:
  port: 8888
  servlet:
    context-path: /api

jwt:
  secret: SHUCOLLEGEOFCOMPUTERENGINEERINGANDSCIENCE22123131
  expiration: 604800000  # 7天（毫秒）

llm:
  base-url: https://api.minimaxi.com/v1
  api-key: sk-cp-X1VcaIrryShpehZjo8Di0MvLWOZeDTNKgZFYzn49-SZn83ETfitlyZD-4bbVYtR0cjG-am93NClVxfpAlyE0WWBd2d8ngtI0mcRuMjqGAZAEJ91b0EGM_i8
  chat-path: /chat/completions
  model: MiniMax-M2.7
  temperature: 1.0
  max-tokens:  1024

user:
  base-path: D:\SHU files\Graduation project\PestDetectionSystem\images
